name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.3'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ${{ github.workspace }}/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Print Go version
        run: go version

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          # The action will run the `run` subcommand; only pass flags here.
          args: --timeout=10m
          # Use latest golangci-lint version (v2.5.0 or newer for Go 1.25.3)
          version: v2.5.0
          install-mode: binary

      - name: Run tests
        run: make test
