name: Release Please

# IMPORTANT: This workflow requires the following repository setting to be enabled:
# Settings > Actions > General > Workflow permissions
# ✓ "Allow GitHub Actions to create and approve pull requests"
#
# Without this setting enabled, the workflow will fail with:
# "GitHub Actions is not permitted to create or approve pull requests"
#
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
